/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/_dashboard'

// Create Virtual Childrens

const DashboardUsersLazyImport = createFileRoute('/_dashboard/users')()
const DashboardSettingsLazyImport = createFileRoute('/_dashboard/settings')()
const DashboardPlayersLazyImport = createFileRoute('/_dashboard/players')()
const DashboardOperatorsLazyImport = createFileRoute('/_dashboard/operators')()
const DashboardGameruesLazyImport = createFileRoute('/_dashboard/gamerules')()
const DashboardConnectionLazyImport = createFileRoute(
  '/_dashboard/connection',
)()
const DashboardBansLazyImport = createFileRoute('/_dashboard/bans')()
const DashboardAllowlistLazyImport = createFileRoute('/_dashboard/allowlist')()
const DashboardIndexLazyImport = createFileRoute('/_dashboard/')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersLazyRoute = DashboardUsersLazyImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() => import('./routes/_dashboard.users.lazy').then((d) => d.Route))

const DashboardSettingsLazyRoute = DashboardSettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.settings.lazy').then((d) => d.Route),
)

const DashboardPlayersLazyRoute = DashboardPlayersLazyImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.players.lazy').then((d) => d.Route),
)

const DashboardOperatorsLazyRoute = DashboardOperatorsLazyImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.operators.lazy').then((d) => d.Route),
)

const DashboardGamerulesLazyRoute = DashboardGameruesLazyImport.update({
  id: '/gamerules',
  path: '/gamerules',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.gamerules.lazy').then((d) => d.Route),
)

const DashboardConnectionLazyRoute = DashboardConnectionLazyImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.connection.lazy').then((d) => d.Route),
)

const DashboardBansLazyRoute = DashboardBansLazyImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.bans.lazy').then((d) => d.Route),
)

const DashboardAllowlistLazyRoute = DashboardAllowlistLazyImport.update({
  id: '/allowlist',
  path: '/allowlist',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.allowlist.lazy').then((d) => d.Route),
)

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard.index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/allowlist': {
      id: '/_dashboard/allowlist'
      path: '/allowlist'
      fullPath: '/allowlist'
      preLoaderRoute: typeof DashboardAllowlistLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/bans': {
      id: '/_dashboard/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof DashboardBansLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/connection': {
      id: '/_dashboard/connection'
      path: '/connection'
      fullPath: '/connection'
      preLoaderRoute: typeof DashboardConnectionLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/gamerules': {
      id: '/_dashboard/gamerules'
      path: '/gamerules'
      fullPath: '/gamerules'
      preLoaderRoute: typeof DashboardGameruesLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/operators': {
      id: '/_dashboard/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof DashboardOperatorsLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/players': {
      id: '/_dashboard/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof DashboardPlayersLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersLazyImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardAllowlistLazyRoute: typeof DashboardAllowlistLazyRoute
  DashboardBansLazyRoute: typeof DashboardBansLazyRoute
  DashboardConnectionLazyRoute: typeof DashboardConnectionLazyRoute
  DashboardGamerulesLazyRoute: typeof DashboardGamerulesLazyRoute
  DashboardOperatorsLazyRoute: typeof DashboardOperatorsLazyRoute
  DashboardPlayersLazyRoute: typeof DashboardPlayersLazyRoute
  DashboardSettingsLazyRoute: typeof DashboardSettingsLazyRoute
  DashboardUsersLazyRoute: typeof DashboardUsersLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardAllowlistLazyRoute: DashboardAllowlistLazyRoute,
  DashboardBansLazyRoute: DashboardBansLazyRoute,
  DashboardConnectionLazyRoute: DashboardConnectionLazyRoute,
  DashboardGamerulesLazyRoute: DashboardGamerulesLazyRoute,
  DashboardOperatorsLazyRoute: DashboardOperatorsLazyRoute,
  DashboardPlayersLazyRoute: DashboardPlayersLazyRoute,
  DashboardSettingsLazyRoute: DashboardSettingsLazyRoute,
  DashboardUsersLazyRoute: DashboardUsersLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexLazyRoute
  '/allowlist': typeof DashboardAllowlistLazyRoute
  '/bans': typeof DashboardBansLazyRoute
  '/connection': typeof DashboardConnectionLazyRoute
  '/gamerules': typeof DashboardGamerulesLazyRoute
  '/operators': typeof DashboardOperatorsLazyRoute
  '/players': typeof DashboardPlayersLazyRoute
  '/settings': typeof DashboardSettingsLazyRoute
  '/users': typeof DashboardUsersLazyRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexLazyRoute
  '/allowlist': typeof DashboardAllowlistLazyRoute
  '/bans': typeof DashboardBansLazyRoute
  '/connection': typeof DashboardConnectionLazyRoute
  '/gamerules': typeof DashboardGamerulesLazyRoute
  '/operators': typeof DashboardOperatorsLazyRoute
  '/players': typeof DashboardPlayersLazyRoute
  '/settings': typeof DashboardSettingsLazyRoute
  '/users': typeof DashboardUsersLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexLazyRoute
  '/_dashboard/allowlist': typeof DashboardAllowlistLazyRoute
  '/_dashboard/bans': typeof DashboardBansLazyRoute
  '/_dashboard/connection': typeof DashboardConnectionLazyRoute
  '/_dashboard/gamerules': typeof DashboardGamerulesLazyRoute
  '/_dashboard/operators': typeof DashboardOperatorsLazyRoute
  '/_dashboard/players': typeof DashboardPlayersLazyRoute
  '/_dashboard/settings': typeof DashboardSettingsLazyRoute
  '/_dashboard/users': typeof DashboardUsersLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/allowlist'
    | '/bans'
    | '/connection'
    | '/gamerules'
    | '/operators'
    | '/players'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/allowlist'
    | '/bans'
    | '/connection'
    | '/gamerules'
    | '/operators'
    | '/players'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/allowlist'
    | '/_dashboard/bans'
    | '/_dashboard/connection'
    | '/_dashboard/gamerules'
    | '/_dashboard/operators'
    | '/_dashboard/players'
    | '/_dashboard/settings'
    | '/_dashboard/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
